trigger: none

pool:
  name: Default  # Self-hosted agent pool

variables:
  TF_WORKING_DIR: 'environments/primary'

steps:
- task: Bash@3
  displayName: 'Terraform Init'
  inputs:
    targetType: 'inline'
    script: |
      cd $(TF_WORKING_DIR)
      terraform init
  env:
    TF_VAR_client_id: $(ARM_CLIENT_ID)
    TF_VAR_client_secret: $(ARM_CLIENT_SECRET)
    TF_VAR_subscription_id: $(ARM_SUBSCRIPTION_ID)
    TF_VAR_tenant_id: $(ARM_TENANT_ID)

- task: Bash@3
  displayName: 'Terraform Plan'
  inputs:
    targetType: 'inline'
    script: |
      cd $(TF_WORKING_DIR)
      terraform plan -out=tfplan
  env:
    TF_VAR_client_id: $(ARM_CLIENT_ID)
    TF_VAR_client_secret: $(ARM_CLIENT_SECRET)
    TF_VAR_subscription_id: $(ARM_SUBSCRIPTION_ID)
    TF_VAR_tenant_id: $(ARM_TENANT_ID)

- task: Bash@3
  displayName: 'Terraform Apply'
  inputs:
    targetType: 'inline'
    script: |
      cd $(TF_WORKING_DIR)
      terraform apply -auto-approve tfplan
  env:
    TF_VAR_client_id: $(ARM_CLIENT_ID)
    TF_VAR_client_secret: $(ARM_CLIENT_SECRET)
    TF_VAR_subscription_id: $(ARM_SUBSCRIPTION_ID)
    TF_VAR_tenant_id: $(ARM_TENANT_ID)
