variables:
  TF_WORKING_DIR: 'environments/primary'

steps:
- task: Bash@3
  displayName: 'Terraform Init'
  inputs:
    targetType: 'inline'
    script: |
      cd $(TF_WORKING_DIR)
      terraform init -reconfigure
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
    TF_VAR_tenant_id: $(ARM_TENANT_ID)
    TF_VAR_object_id: $(ARM_OBJECT_ID)

- task: Bash@3
  displayName: 'Terraform Plan'
  inputs:
    targetType: 'inline'
    script: |
      cd $(TF_WORKING_DIR)
      terraform plan
  env:
    TF_VAR_tenant_id: $(ARM_TENANT_ID)
    TF_VAR_object_id: $(ARM_OBJECT_ID)

- task: Bash@3
  displayName: 'Terraform Apply'
  inputs:
    targetType: 'inline'
    script: |
      cd $(TF_WORKING_DIR)
      terraform apply -auto-approve
  env:
    TF_VAR_tenant_id: $(ARM_TENANT_ID)
    TF_VAR_object_id: $(ARM_OBJECT_ID)
