trigger: none

pool:
  name: Default

variables:
  TF_WORKING_DIR: 'environments/primary'

steps:
- script: terraform -version
  displayName: 'Verify preinstalled Terraform version'

- script: |
    cd $(TF_WORKING_DIR)
    terraform init
  displayName: 'Terraform Init'

- script: |
    cd $(TF_WORKING_DIR)
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: |
    cd $(TF_WORKING_DIR)
    terraform apply tfplan
  displayName: 'Terraform Apply'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
