trigger: none

pool:
  name: Default

variables:
  TF_WORKING_DIR: 'environments/primary'

steps:
- script: terraform -version
  displayName: 'Verify preinstalled Terraform version'

- script: |
    cd $(TF_WORKING_DIR)
    terraform init
  displayName: 'Terraform Init'

- script: |
    cd $(TF_WORKING_DIR)
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: |
    cd $(TF_WORKING_DIR)
    terraform apply tfplan
  displayName: 'Terraform Apply'
  env:
    TF_VAR_client_id: $(ARM_CLIENT_ID)
    TF_VAR_client_secret: $(ARM_CLIENT_SECRET)
    TF_VAR_subscription_id: $(ARM_SUBSCRIPTION_ID)
    TF_VAR_tenant_id: $(ARM_TENANT_ID)

