trigger: none

pool:
  name: Default

variables:
  TF_WORKING_DIR: 'environments/backend'

steps:
- task: Bash@3
  displayName: 'Terraform Init - Upgrade Provider'
  inputs:
    targetType: 'inline'
    script: |
      cd $(TF_WORKING_DIR)
      rm -rf .terraform .terraform.lock.hcl
      terraform init -upgrade -reconfigure
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)


- task: Bash@3
  displayName: 'Terraform Apply Backend Infra'
  inputs:
    targetType: 'inline'
    script: |
      cd $(TF_WORKING_DIR)
      terraform apply -auto-approve
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
